---
- name: Copy .bash_aliases file to vagrant
  copy:
    src: config_files/.bash_aliases
    dest: "{{ vagrant_home }}/.bash_aliases"
    owner: vagrant
    group: vagrant
    mode: 0644
    force: no

- name: Create initial gitconfig file 
  template:
    src: gitconfig.j2
    dest: "{{ vagrant_home }}/.gitconfig"
    owner: vagrant
    group: vagrant
    mode: 0644
