---
dependencies:
  - tgg.git
  - tgg.apache
  - tgg.mysql
  - tgg.php
  - tgg.php-mysql
  - tgg.composer
  - tgg.drush

galaxy_info:
  author: geerlingguy
  description: Install Drupal - a world class CMS
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - development
    - web
