---
- name: Waiting 60 seconds for F5 VPN Connection
  wait_for:
    host: "{{ drupal_wget_dump }}"
    timeout: 60
  when: drupal_domain != 'sandbox8' and drupal_domain != 'sandbox7' and drupal_domain != 'drupal7'

- name: Download MySQL Dump for domain
  get_url:
    url: "{{ drupal_mysql_dump }}"
    dest: "/tmp/{{ drupal_domain }}.sql.gz"
  when: drupal_domain != 'sandbox8' and drupal_domain != 'sandbox7' and drupal_domain != 'drupal7'

- name: Create MySQL database for Drupal.
  mysql_db:
    db: "{{ drupal_mysql_database }}"
    state: present

- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ drupal_mysql_user }}"
    host: "{{ item }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
    password: "{{ drupal_mysql_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
