---
- name: Copy database dump to vagrant server
  copy: src=//Users/karyn/Sites/dumps/housing.sql.gz dest=/tmp/housing.sql.gz

- name: Create a MySQL database for Drupal.
  mysql_db:
    db: "{{ drupal_mysql_database }}"
    state: import
    target: "/tmp/{{ drupal_domain}}.sql.gz"

- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ drupal_mysql_user }}"
    host: "{{ item }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
    password: "{{ drupal_mysql_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

# - name: Import database.sql to mysql database created above.

#   mysql_db:
#     state: import
#     name: "{{ drupal_domain }}"

