---
# Download Drupal using drush (--no-cache prevents checksum error).
# - name: "Drupal: Download Drupal Core."
#   command:
#     drush dl drupal-{{ drupal_core_version }} --no-cache
#     creates={{ drupal_core_path }}/index.php
#     chdir=/var/www
# Get ssh keys

- name: Create folder for root ssh key
  file:
    path: ~/.ssh
    state: directory
    mode: 0744

- name: Send key to remote deploy user
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/priv_key
    mode: 0600

# Download Drupal using Git.
- name: Check out Repo to the specified location.
  git:
    repo: "{{ drupal_repo_url }}"
    dest: "{{ drupal_core_path }}"
    accept_hostkey: yes
    key_file: "~/.ssh/priv_key"

# Install Drupal for site
- name: Install Drupal.
  command: >
    drush si -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_admin_name }}
    --account-pass={{ drupal_admin_password}}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ drupal_mysql_database }}
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/sites/default/settings.php

- name: Set ownership of /var/www/web/ drupal_domain_path
  file:
    path: "{{ drupal_core_path }}"
    #mode: 0775
    owner: vagrant
    group: vagrant
    state: directory
    recurse: yes

# SEE: https://drupal.org/node/2121849#comment-8413637
- name: Set permissions properly on settings.php.
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: 0644

- name: Set permissions properly on files directory.
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes

- name: Create symbolic link to new web directory in home
  file:
    src: "{{ drupal_core_path }}"
    dest: "/home/vagrant/{{ drupal_domain }}"
    state: link
