---
- include: db.yml
- include: web.yml
- include: drupal.yml
- include: importdb.yml
  when: "{{ build_exceptions }}"
- include: bundle.yml
- include: site-settings.yml
- include: wysiwyg.yml
  when: drupal_domain == 'sandbox7' or drupal_domain == 'drupal7'
