---
- name: Download WYSIWYG Editor
  get_url:
    url: "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.2/ckeditor_3.6.6.2.zip"
    dest: "{{ drupal_core_path }}/sites/all/libraries"
  when: drupal_domain == 'sandbox7' or drupal_domain == 'drupal7'

# Set file system locations
- name: Unzip ckeditor
  command: >
    unzip ckeditor_3.6.6.2.zip
    chdir={{ drupal_core_path }}/sites/all/libraries
  when: drupal_domain == 'sandbox7' or drupal_domain == 'drupal7'
