---
# Download the WYSIWYG Editor
- name: Download WYSIWYG Editor
  get_url:
    url: "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.2/ckeditor_3.6.6.2.zip"
    dest: "/tmp/ckeditor_3.6.6.2.zip"

# Unzip CKEditor
- name: Unzip ckeditor
  unarchive:
    src: "/tmp/ckeditor_3.6.6.2.zip"
    dest: "{{ drupal_core_path }}/sites/all/libraries/ckeditor"
