---
# Ansible playbook for a Drupal LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: hdsvm
  gather_facts: yes
  remote_user: vagrant
  sudo: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php5-5.6'

  roles:
    - roles/hds.firewall
    - roles/hds.ntp
    - roles/hds.postfix
    - roles/hds.mysql
    - roles/hds.apache
    - roles/hds.php
    - roles/hds.php-mysql
    - roles/hds.composer
    - roles/hds.drush
    - roles/hds.drupal
