---
# Ansible playbook for HDS IT Drupal Local Development sites.
#
# @author Karyn Cassio (2016).

- hosts: local-dev
  gather_facts: yes
  remote_user: vagrant
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php5-5.6'

    #- name: print out hostvars
    #  debug: var=hostvars[inventory_hostname].ansible_hostname

  vars_prompt:
   - name: "git_name"
     prompt: "What is your full name for git? (Name will not be echoed.)"
     private: yes

   - name: "git_email"
     prompt: "What is your CU Email address? (Email will not be echoed.)"
     private: yes

  roles:
    - roles/hds.debian_mods
    - roles/hds.firewall
    - roles/hds.ntp
    - roles/hds.postfix
    - roles/hds.mysql
    - roles/hds.apache
    - roles/hds.php
    - roles/hds.php-mysql
    - roles/hds.composer
    - roles/hds.drush
    - roles/hds.drupal
    - roles/hds.user_config
