---
# Your site's domain name (e.g. 'oncampus').
drupal_domain: "{{ hostvars[inventory_hostname].ansible_hostname }}"

# Drupal private files path
drupal_private_path: "/var/www/web/{{ drupal_domain }}.dev/private"

# The path where Drupal will be downloaded and installed.
drupal_core_path: "/var/www/web/{{ drupal_domain }}.dev/public"

# Your Drupal site name.
drupal_site_name: "{{ drupal_domain }} Dev"

# Your Drupal site admin account credentials.
drupal_admin_name: admin
drupal_admin_password: admin

# The webserver you're running (e.g. 'apache2', 'httpd', 'nginx').
drupal_webserver_daemon: apache2

# Drupal MySQL database username and password.
drupal_mysql_user: "{{ drupal_domain }}"
drupal_mysql_password: password
drupal_mysql_database: "{{ drupal_domain }}"

# The Drupal git url from which Drupal will be cloned.
drupal_repo_url: "git@bitbucket.org:hdscode/{{ drupal_domain }}.git"

drupal_repo: "http://git.drupal.org/project/drupal.git"

# Whether to update the repo above to the latest commit in the branch identified
# by `drupal_core_version` (the git tag or branch) whenever this playbook runs.
drupal_keep_updated: no

# wget URL
drupal_wget_dump: "ndmps.hds.int.colorado.edu"

# Wget URL for MySQL dumps
drupal_mysql_dump: "http://{{ drupal_wget_dump }}/{{ drupal_domain }}.sql.gz"
