---
- name: Copy .bash_aliases file to vagrant
  copy:
    src: config_files/.bash_aliases
    dest: "{{ vagrant_home }}/.bash_aliases"
    owner: vagrant
    group: vagrant
    mode: 0644
    force: no

- name: Create initial gitconfig file 
  template:
    src: gitconfig.j2
    dest: "{{ vagrant_home }}/.gitconfig"
    owner: vagrant
    group: vagrant
    mode: 0644
    force: no 

- name: Create initial known_hosts file for Vagrant user
  copy: 
    src: ~/.ssh/known_hosts
    dest: "{{ vagrant_home }}/.ssh/known_hosts"
    owner: vagrant
    group: vagrant
    mode: 0644
    force: no

- name: Add line for pretty prompt with GIT info
  lineinfile:
    dest: "{{ vagrant_home }}/.bashrc"
    create: yes
    state: present
    line: "export PS1='\\[\\033[01;32m\\]\\u@\\h\\[\\033[01;34m\\] \\w\\[\\033[01;33m\\]$(__git_ps1)\\[\\033[01;34m\\] \\$\\[\\033[00m\\] '"
    regexp: "^export PS1\\="
