---
# - name: Waiting 60 seconds for F5 VPN Connection
#   wait_for:
#     host: "{{ drupal_wget_dump }}"
#     timeout: 60
#   when: "build_exceptions"
#   tags:
#     - dbrefresh
#
# - name: Download MySQL Dump for domain
#   get_url:
#     url: "{{ drupal_mysql_dump }}"
#     dest: "/tmp/{{ drupal_domain }}.sql.gz"
#   when: "build_exceptions"
#   tags:
#     - dbrefresh

- name: Create MySQL database for Drupal.
  mysql_db:
    db: "{{ drupal_mysql_database }}"
    state: present
  tags:
    - dbrefresh

- name: Create a MySQL user for Drupal.
  mysql_user:
    name: "{{ drupal_mysql_user }}"
    host: "{{ item }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
    password: "{{ drupal_mysql_password }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags:
    - dbrefresh
