---
# Set file system locations
- name: Set Private file system path
  command: >
    drush vset file_private_path "{{ drupal_private_path }}"
    chdir={{ drupal_core_path }}
  when: drupal_domain != 'sandbox8' and drupal_domain != 'drupal8'
  tags: dbrefresh

# Turn on devel module
- name: Turn on Devel module
  command: >
    drush en devel -y
    chdir={{ drupal_core_path }}
  when: drupal_domain != 'sandbox8' and drupal_domain != 'sandbox7'
  tags: dbrefresh

# Make sure only administrator email addresses are real.
- name: Obfuscate non-admin email addresses
  command: >
    drush sqlsan --sanitize-email=%name+%uid@colorado.edu --sanitize-password=no -y
    chdir={{ drupal_core_path }}
  when: "build_exceptions"
  tags: dbrefresh
